logging:
  level:
    com.sfg.course.spring6webap: debug

server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:sfg6db
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    rest:
      base-path: /api/v1
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false


